rollouts: true
every: 10
loss_threshold: 0.1
max_steps: 750
num_envs: 256
count: ${rollout.num_envs}
save_rollouts: false
save_failures: false
randomness: low
furniture: ${furniture}
n_parts_assemble: null

