name: diffusion

action_horizon: ${action_horizon}
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
predict_past_actions: ${predict_past_actions}
# Set the flatten obs variable to whatever value is in the diffusion_model sub-config
flatten_obs: ${actor.diffusion_model.flatten_obs}

beta_schedule: squaredcos_cap_v2
prediction_type: epsilon
inference_steps: 16
num_diffusion_iters: 100
clip_sample: true

loss_fn: MSELoss  # MSELoss | L1Loss

projection_dim: 128

defaults:
  - diffusion_model: unet