data:
  test_split: 0.05
  data_subset: null
  dataloader_workers: 16
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  predict_past_actions: ${predict_past_actions}
  augment_image: true
  environment: ${environment}
  task: ${task}
  demo_source: ${demo_source}
  randomness: ${randomness}
  normalization: min_max # min_max, mean_std, none
  demo_outcome: ${demo_outcome}
  pad_after: true
  suffix: null
  include_future_obs: false
  minority_class_power: false
  data_paths_override: null
  load_into_memory: true
  parts_poses_in_robot_frame: ${parts_poses_in_robot_frame}
