training:
  gpu_id: 0
  
  actor_lr: 1e-4
  encoder_lr: ${training.actor_lr}
  clip_grad_norm: false
  clip_sample: true
  mixed_precision: false
  
  num_epochs: 400
  batch_size: 64
  start_epoch: 0
  steps_per_epoch: 400
  
  load_checkpoint_run_id: null
  checkpoint_model: true
  model_save_dir: models
